config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  get 'signup' => 'users#new', as: :sign_up
  post  'signup' => 'users#create'
  
  get 'signin' => 'sessions#new', as: :sign_in
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#delete', as: :sign_out
  
  resources :sessions, only: [:create]

  get 'events/new' => 'events#new'

  post 'events' => 'events#create'

  get 'events/:id' => 'events#show', as: :event

  get 'users/:id/edit' => 'users#edit'

  get 'events/edit' =>'events#edit'

  patch 'events/update' => 'events#update'

  get 'events/destroy'

  get 'vevents' => 'signups#index', as: :vevents

  get 'vevents/new' => 'signups#new', as: :new_vevent

  post 'vevents' => 'signups#create'

  get 'vevents' => 'signups#show'

  resources :users
  resources :events
 

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :users, through: :signups
	has_many :signups
	belongs_to :users
end

app/models/signup.rb
class Signup < ActiveRecord::Base
	belongs_to :event
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :events, through: :signups
	has_many :signups
	belongs_to :events

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
	before_save {self.email = email.downcase}
	
	validates :email, presence: :true,
				format: {with: VALID_EMAIL_REGEX},
				uniqueness: {case_sensitive: false}

	validates :password, length: {minimum: 6}

	before_create :create_remember_token
	has_secure_password
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
	def create_remember_token
		self.remember_token = User.digest(User.new_remember_token)
	end

end

	
	# before_save :hash_password
	
	# def hash_password
	# 	self.password = Digest::SHA1.hexdigest(
	# 	self.password.to_s)
	# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      @events = Event.all
      render action: 'index'
    else
      render action: 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
     redirect_to(@event)   
    else
      render action: 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private
    def event_params
    params.require(:event).permit(:name, :location, :when, :description, :image, :contact_phone, :contact_email)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to current_user
    end
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user  
    else
      render 'new'
    end
  end

  def delete
    sign_out
    redirect_to root_url
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

def index
	@vevents = Signup.all
end

def new
	@signup = Signup.new
	@event_id = params[:format]
	@user_id = current_user.id
end

def show
	@signup = Signup.new
end

def create
	@signup = Signup.new(signup_params)

	if @signup.save
		@signups = Signup.all
		redirect_to @signup
	else
		render 'new'
	end
end

private
	def signup_params
		params.require(:signup).permit(:event_id, :user_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, except: [:new, :create]
  before_action :correct_user, except: [:new, :create] 
	
  def index
		@users = User.all
	end

	def new
    if current_user
      redirect_to current_user
    else 
      @user = User.new
    end
  end

	def create
		@user = User.new(user_params)

  	if @user.save
  	sign_in @user
   	 @users = User.all
    	redirect_to @user
  	else
    	render action: 'new'
    end
	end

  def edit
    @user = User.find(params[:id])

	end

	def update
	    respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to @user, notice: 'User was successfully updated.' }
	        format.json { render :show, status: :ok, location: @user }
	      else
	        format.html { render :edit }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	end

  	def show
  		@user = User.find(params[:id])
		end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to events_path
  end

private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def correct_user
      find_user
      redirect_to(current_user) unless current_user?(@user)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in_user
		unless signed_in?
		redirect_to root_url, notice: "Please sign in."
		end
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end


	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)

	end

	def current_user?(user)
		user == current_user
	end	

	def sign_out
		current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="addNewPage">


<%= form_for(@event) do |f| %>
<div class="formAddEventTile">
	<div class="addEventInput">
		<h1 id="addEventTitle">Edit <%= @event.name %></h1>
			<%= f.text_field :name, placeholder: "Name" %><br/>
			<%= f.text_field :location , placeholder: "Location" %><br/>
			<%= f.text_field :when , placeholder: "When" %><br/>
			<%= f.text_field :description , placeholder: "Description" %><br/>
			<%= f.text_field :image , placeholder: "Main Image" %><br/>
			<%= f.text_field :contact_phone , placeholder: "Contact Phone" %><br/>
			<%= f.text_field :contact_email , placeholder: "Contact Email" %><br/>
			<%= link_to 'Back', events_path, :class => "btn btn-primary" %>
			<%= f.submit  :class => "btn btn-success" %>
			<%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>

	</div>
</div>

<% end %>
</div>

app/views/events/index.html.erb
<div class="addNewPage">

	<h1>Events Near You</h1>
	
	<% @events.each do |event| %>
		<%= link_to event do %>
			<div class="eventTile">
				<h3><%= event.name %></h3>
				<p><%= event.location %></p>
				<p><%= l event.when, format: :long %></p>
				<p><%= event.description %></p>
				<p>Phone: <%= event.contact_phone %></p>
				<p><%= event.contact_email %></p>
				<p><%= image_tag(( event.image ), :class => "style_image") %></p>
			</div>
		<% end %>	
	<% end %>
</div>

app/views/events/new.html.erb
<div class="addNewPage">
	
	<%= form_for(@event) do |f| %>
	
		<div class="formAddEventTile">
			<div class="addEventInput">
				<h1 id="addEventTitle">Add New Event!</h1>
				<%= f.text_field :name, placeholder: "Name" %><br/>
				<%= f.text_field :location , placeholder: "Location" %><br/>
				<%= f.datetime_select :when , placeholder: "Date and Time" %><br/>
				<%= f.text_field :description , placeholder: "Description" %><br/>
				<%= f.text_field :image , placeholder: "Main Image" %><br/>
				<%= f.text_field :contact_phone , placeholder: "Contact Phone" %><br/>
				<%= f.text_field :contact_email , placeholder: "Contact Email" %><br/>
				<%= link_to 'Back', events_path, :class => "btn btn-primary" %>
				<%=  f.submit class: "btn btn-success" %>
			</div>
	    </div>

	<% end %>
</div>

app/views/events/show.html.erb
<div class="showPage">

<div class="jumbotron">
  <h1><%= @event.name %></h1>
</div> 

  <div class="row">
   <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img><%= image_tag(( @event.image ), :class => "showImage") %>>  
      <div class="caption">
        
      <p><%= @event.location %></p>
      <p><%= @event.description %></p>
      <p><%= @event.contact_phone %></p>
      <p><%= @event.contact_email %></p>
       <%= link_to 'Back', events_path, :class => "btn btn-primary" %>
       <%= link_to 'Edit', edit_event_path, :class => "btn btn-warning" %>
       <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
       <%= link_to 'Click Here To Volunteer!', new_vevent_path(@event), :class => "btn btn-success" %>
      
    </div>
  </div>
 </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>VolunteerApp</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
      	
	    	<a href="/events" class="navbar-brand">Volunteer.ly</a>
        
          
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <button type="button" class="btn btn-info dropdown-toggle navbar-btn" data-toggle="dropdown">
              Menu <span class="caret"></span>
              </button> 
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", sign_out_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <%= link_to "Sign in", sign_in_path, class: "btn btn-info navbar-btn" %>
          <% end %>
        </ul>
        <ul class="nav navbar-right">
          <li><div><%= link_to "Add New Event", ( new_event_path ), class: "btn btn-primary navbar-btn" %></div>
           </li> 

        </ul>
      </nav>
    </div>
  </div>
</header>

  <body>

	<%= yield %>

	</body>
</html>

app/views/signups/index.html.erb
<h1>Event's you've volunteer for</h1>
	
	<% @vevents.each do |vevent| %>
		<%= link_to vevent do %>
			<div>
				<p><%= Event.find(vevent.event_id).name %> </p>

			</div>
		<% end %>	
	<% end %>
</div>

app/views/signups/new.html.erb
<%= form_for(@signup, url: vevents_path) do |f| %>


<%= f.hidden_field :user_id, :value => @user_id %>
<%= f.hidden_field :event_id, :value => @event_id %>

<%= f.submit "Confirm intent to volunteer", class: "btn btn-large btn-primary" %>

<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :zip_cope %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= form_for(@user) do |f| %>

	<%= f.text_field :name, placeholder: 'Update Name'%>
	<%= f.text_field :email, placeholder: 'Update Email'%>
	<%= f.text_field :password, placeholder: 'Update Password'%>
	<%= f.text_field :password_confirmation, placeholder: 'Confirm New Password'%>
	<%= f.submit %>

	<%= link_to 'Delete You Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %> 

<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.remember_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="logInForm">
    <div class="addEventInput">
        <h1 id="addEventTitle">Create a New Account!</h1>
          <div class="row">
            <%= form_for(@user) do |f| %>

			  <% if @user.errors.any? %>
			    <div id="error_explanation">
			      <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:
			      <ul>
			        <% @user.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			        <% end %>
			      </ul>
			    </div>
			  <% end %>
				<%= f.text_field :name, placeholder: 'Name'%><br/>
				<%= f.text_field :email, placeholder: 'Email'%><br/>
				<%= f.text_field :password, placeholder: 'Password'%><br/>
				<%= f.text_field :password_confirmation, placeholder: 'Confirm Password'%><br/>
				<%= f.submit "Create Account", class: "btn btn-info" %>
				<% end %>
      	</div>
    </div>
</div>

app/views/users/show.html.erb
<h1>Thank you for volunteering, <%= @user.name %>! </h1>
<%= link_to "Here are the event's you've signed up for", vevents_path %><br/>

<%= link_to "Volunteer for an Event", events_path %> | <%= link_to 'Edit Your Profile', edit_user_path %> | <%= link_to 'Delete You Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %> 